// Package honk implements an UltraHonk proof verifier for BN254-based SNARK proofs.
//
// UltraHonk is Aztec's proving system featuring sumcheck-based verification,
// Shplemini/KZG polynomial commitment scheme, and Fiat-Shamir transcript generation.
// This package provides a pure-Go verifier compatible with proofs generated by
// Aztec's Barretenberg library.
//
// The verifier supports circuits with up to 2^28 gates and handles arithmetic,
// permutation, lookup, delta range, elliptic curve, auxiliary, and Poseidon2
// relation checks.
package honk

import (
	"fmt"
	"math/big"

	"github.com/consensys/gnark-crypto/ecc/bn254"
	"github.com/consensys/gnark-crypto/ecc/bn254/fr"
)

// negHalfModP = (P - 1) / 2, used in the arithmetic relation accumulator.
var negHalfModP fr.Element

func init() {
	if _, err := negHalfModP.SetString("0x183227397098d014dc2822db40c0ac2e9419f4243cdcb848a1f0fac9f8000000"); err != nil {
		panic(fmt.Sprintf("honk: failed to initialize negHalfModP: %v", err))
	}
}

// mustFromHex parses a hex string into a field element, panicking on failure.
// Used only for compile-time constants; never called with user input.
func mustFromHex(s string) fr.Element {
	var e fr.Element
	if _, err := e.SetString(s); err != nil {
		panic(fmt.Sprintf("honk: invalid hex constant %q: %v", s, err))
	}
	return e
}

func frFrom(v uint64) fr.Element {
	var e fr.Element
	e.SetUint64(v)
	return e
}

func frNeg(a fr.Element) fr.Element {
	var r fr.Element
	r.Neg(&a)
	return r
}

func frAdd(a, b fr.Element) fr.Element {
	var r fr.Element
	r.Add(&a, &b)
	return r
}

func frSub(a, b fr.Element) fr.Element {
	var r fr.Element
	r.Sub(&a, &b)
	return r
}

func frMul(a, b fr.Element) fr.Element {
	var r fr.Element
	r.Mul(&a, &b)
	return r
}

func frSqr(a fr.Element) fr.Element {
	var r fr.Element
	r.Mul(&a, &a)
	return r
}

func frInv(a fr.Element) fr.Element {
	var zero fr.Element
	if a == zero {
		panic("honk: inverse of zero field element")
	}
	var r fr.Element
	r.Inverse(&a)
	return r
}

func frDiv(a, b fr.Element) fr.Element {
	var r fr.Element
	r.Div(&a, &b)
	return r
}

// convertProofPoint converts a split-encoded G1ProofPoint to a bn254.G1Affine.
// In the proof format, x = x_0 | (x_1 << 136) and y = y_0 | (y_1 << 136).
func convertProofPoint(p G1ProofPoint) bn254.G1Affine {
	shift := new(big.Int).Lsh(big.NewInt(1), 136)

	x0 := new(big.Int)
	x1 := new(big.Int)
	y0 := new(big.Int)
	y1 := new(big.Int)

	p.X0.BigInt(x0)
	p.X1.BigInt(x1)
	p.Y0.BigInt(y0)
	p.Y1.BigInt(y1)

	xBig := new(big.Int).Add(x0, new(big.Int).Mul(x1, shift))
	yBig := new(big.Int).Add(y0, new(big.Int).Mul(y1, shift))

	var point bn254.G1Affine
	point.X.SetBigInt(xBig)
	point.Y.SetBigInt(yBig)
	return point
}

// negateG1 negates a G1 affine point (negate Y coordinate mod q).
func negateG1(p bn254.G1Affine) bn254.G1Affine {
	p.Neg(&p)
	return p
}
